export const LOGIN = 'LOGIN';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const VIEW_MEMBERSHIPS = 'VIEW_MEMBERSHIPS';

export const ADD_NEW_BOOK ='ADD_NEW_BOOK';
export const ADD_NEW_BOOK_SUCCESS ='ADD_NEW_BOOK_SUCCESS';
export const ADD_NEW_BOOK_FAIL ='ADD_NEW_BOOK_FAIL';
export const VIEW_BOOK_LIST = 'VIEW_BOOK_LIST';
export const VIEW_BOOK_DETAILS_SUCCESS = 'VIEW_BOOK_DETAILS_SUCCESS';
export const CHECK_BOOK_AVAILABILITY = 'CHECK_BOOK_AVAILABILITY';
export const RESERVE_BOOK = 'RESERVE_BOOK';
export const RESERVE_BOOK_SUCCESS = 'RESERVE_BOOK_SUCCESS';
export const RESERVE_BOOK_FAIL = 'RESERVE_BOOK_FAIL';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const BOOK_AVAILABILITY = 'BOOK_AVAILABILITY';

export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';

export const ADD_NEW_MOVIE = 'ADD_NEW_MOVIE';
export const ADD_NEW_MOVIE_SUCCESS = 'ADD_NEW_MOVIE_SUCCESS';
export const ADD_NEW_MOVIE_FAIL = 'ADD_NEW_MOVIE_FAIL';
export const VIEW_MOVIES_LIST = 'VIEW_MOVIES_LIST';
export const VIEW_MOVIE_DETAILS_SUCCESS = 'VIEW_MOVIE_DETAILS_SUCCESS';

export const VIEW_USERS_LIST = 'VIEW_USERS_LIST';
export const VIEW_USER_DETAILS_SUCCESS = 'VIEW_USER_DETAILS_SUCCESS';

export const GET_RESERVATIONS_LIST = 'GET_RESERVATIONS_LIST';
export const GET_BOOKS_RESERVATIONS_LIST_BY_USER = 'GET_BOOKS_RESERVATIONS_LIST_BY_USER';
export const GET_VIDEOS_RESERVATIONS_LIST_BY_USER = 'GET_VIDEOS_RESERVATIONS_LIST_BY_USER';