export const LOGIN = 'LOGIN';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const VIEW_MEMBERSHIPS = 'VIEW_MEMBERSHIPS';

export const ADD_NEW_BOOK ='ADD_NEW_BOOK';
export const ADD_NEW_BOOK_SUCCESS ='ADD_NEW_BOOK_SUCCESS';
export const ADD_NEW_BOOK_FAIL ='ADD_NEW_BOOK_FAIL';
export const VIEW_BOOK_LIST = 'VIEW_BOOK_LIST';
export const VIEW_BOOK_DETAILS_SUCCESS = 'VIEW_BOOK_DETAILS_SUCCESS';
export const CHECK_BOOK_AVAILABILITY = 'CHECK_BOOK_AVAILABILITY';
export const RESERVE_BOOK = 'RESERVE_BOOK';
export const RESERVE_BOOK_SUCCESS = 'RESERVE_BOOK_SUCCESS';
export const RESERVE_BOOK_FAIL = 'RESERVE_BOOK_FAIL';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const BOOK_AVAILABILITY = 'BOOK_AVAILABILITY';
export const SEARCH_GOOGLE_BOOKS = 'SEARCH_GOOGLE_BOOKS';
export const REQUEST_GOOGLE_BOOKS = 'REQUEST_GOOGLE_BOOKS';
export const REQUEST_GOOGLE_BOOKS_SUCCESS = 'REQUEST_GOOGLE_BOOKS_SUCCESS';
export const REQUEST_GOOGLE_BOOKS_ERROR = 'REQUEST_GOOGLE_BOOKS_ERROR';
export const FETCH_REQUESTED_BOOKS = 'FETCH_REQUESTED_BOOKS';
export const PURCHASE_BOOKS = 'PURCHASE_BOOKS';
export const PURCHASE_BOOKS_SUCCESS = 'PURCHASE_BOOKS_SUCCESS';
export const PURCHASE_BOOKS_ERROR = 'PURCHASE_BOOKS_ERROR';

export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';

export const ADD_NEW_MOVIE = 'ADD_NEW_MOVIE';
export const ADD_NEW_MOVIE_SUCCESS = 'ADD_NEW_MOVIE_SUCCESS';
export const ADD_NEW_MOVIE_FAIL = 'ADD_NEW_MOVIE_FAIL';
export const VIEW_MOVIES_LIST = 'VIEW_MOVIES_LIST';
export const VIEW_MOVIE_DETAILS_SUCCESS = 'VIEW_MOVIE_DETAILS_SUCCESS';

export const VIEW_USERS_LIST = 'VIEW_USERS_LIST';
export const VIEW_USER_DETAILS_SUCCESS = 'VIEW_USER_DETAILS_SUCCESS';
export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';

export const GET_ALL_BOOK_RESERVATIONS_LIST = 'GET_ALL_BOOK_RESERVATIONS_LIST';
export const GET_ALL_MOVIE_RESERVATIONS_LIST = 'GET_ALL_MOVIE_RESERVATIONS_LIST';
export const GET_BOOKS_RESERVATIONS_LIST_BY_USER = 'GET_BOOKS_RESERVATIONS_LIST_BY_USER';
export const GET_VIDEOS_RESERVATIONS_LIST_BY_USER = 'GET_VIDEOS_RESERVATIONS_LIST_BY_USER';
export const VIEW_COMMENTS = 'VIEW_COMMENTS';
export const POST_COMMENT = 'POST_COMMENT';
export const PAYMENT = 'PAYMENT';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';

export const CSV_LOAD = 'CSV_LOAD';
export const CSV_SAVE = 'CSV_SAVE';
export const SCRAP_START = 'SCRAP_START';
export const SCRAP_STATUS = 'SCRAP_STATUS';
export const GET_SCRAP = 'GET_SCRAP';